openapi: 3.0.0
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-upstream: 'http://backend_server'
info:
  title: Brightcove Player Management API Reference
  description: |-
    Reference for the Brightcove Player Management API, used to manipulate players, player configurations and child players (embeds). To test API requests, you can use our [API Testing Tools](/getting-started/concepts-testing-tools-brightcove-apis.html). Popular testing tools include:

      - [cURL](https://general.support.brightcove.com/developer/concepts-set-curl.html)
      - [Postman](/general/use-postman-api-requests.html) - note that the tutorial here uses the Player Management API as an example
      - [Insomnia](/general/use-insomnia-api-requests.html) - note that the tutorial here uses the Player Management API as an example

    If you haven't gone through [Step-by-Step: Player Management](/player-management/getting-started/step-step-player-management.html), it's highly recommended you start there. You'll get security set up and learn some of the basics of using the Player Management API.

    If you are working with this API for the first time, read the [Player Management API Overview](/player-management/getting-started/overview-player-management-api.html).

    Remember that after making any configuration changes you **MUST** re-publish your player. **Note:** Fields in configuration objects need to be set only if you wish to change their values. Fields in configuration objects will be displayed in the response only if explicitly set. For information on authenticating API requests, see [OAuth Overview](/oauth/getting-started/overview-oauth-api-v4.html).

    For additional in-depth guides to features of the API, see the **[general documentation](/player-management/references/index.html)**.

    Base URL: https://players.api.brightcove.com/v2
  version: 2.0.0
  x-bc-access: public
servers:
  - url: 'https://players.api.brightcove.com/v2'
    variables: {}
tags:
  - name: Players
    description: Operations for managing players.
  - name: Player Configurations
    description: Operations for managing player configurations.
  - name: Plugin Registry
    description: Operations for working with the player plugin registry.
  - name: Player Embeds
    description: Operations for managing player embeds (child players).
  - name: Embed Configurations
    description: Operations for managing player embed (child player) configurations.
paths:
  '/accounts/{account_id}/players':
    get:
      tags:
        - Players
      summary: Get a list of players
      description: Get a list of players
      operationId: GetPlayers
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Players
      description: >-
        Create a player. The POST method creates a player by submitting a player
        configuration. The properties of Brightcove Player you can manipulate
        with player management are detailed in the **Request Body Fields**
        section below. To create a player, a publisher must decide what
        properties the final player will have. If no properties are given at
        creation, a blank player will be created with only the base player skin
        applied to the player. A user may then use an HTTP PATCH method to
        update properties after the player has been created.
      summary: Create a player
      operationId: CreatePlayer
      security:
        - BC_OAuth2:
          - video-cloud/player/all
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/players/{player_id}':
    get:
      tags:
        - Players
      summary: Get a single player
      description: Get a player by ID
      operationId: GetPlayer
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Players
      description: >-
        Update a single player. The PATCH method can be used on a single player
        to do a VERY limited update. The only fields you can update in this
        manner are the `name` and `description` properties. All other player
        configuration must be done via the **PLAYER CONFIGURATIONS** APIs,
        detailed below.
      summary: Update a player by ID
      operationId: UpdatePlayer
      security:
        - BC_OAuth2:
          - video-cloud/player/all
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Players
      description: Delete a player and all embeds associated with it.
      summary: Delete a player by ID
      operationId: DeletePlayer
      security:
        - BC_OAuth2:
          - video-cloud/player/all
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/players/{player_id}/publish':
    post:
      tags:
        - Players
      summary: Publish a player
      description: Publish a player for optimization and production use.
      operationId: PublishPlayer
      security:
        - BC_OAuth2:
          - video-cloud/player/all
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/players/{player_id}/configuration/{branch}':
    get:
      tags:
        - Player Configurations
      summary: Get player configuration
      description: Get a preview or published player configuration
      operationId: GetPlayerConfiguration
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/players/{player_id}/configuration':
    patch:
      tags:
        - Player Configurations
      summary: Update player configuration
      description: Update a player configuration
      operationId: UpdatePlayerConfiguration
      security:
        - BC_OAuth2:
          - video-cloud/player/all
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/plugins':
    get:
      tags:
        - Plugin Registry
      summary: Get all plugins
      description: Get all plugins
      operationId: GetAllPlugin
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/plugins/{plugin_id}':
    get:
      tags:
        - Plugin Registry
      summary: Get a single plugin
      description: Get a single plugin
      operationId: GetPlugin
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/players/{player_id}/embeds':
    get:
      tags:
        - Player Embeds
      summary: Get all the embeds for a player.
      description: Get all the embeds (child players) for a player.
      operationId: GetEmbeds
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Player Embeds
      description: >-
        Create an embed (child player) for a player. Note that the initial
        creation of the embed is automatically published. Any changes to the
        embed thereafter will need to be published. When creating the embed, the
        body must be an object representing configuration settings for the new
        embed. By default when you create an embed, data in the embed overrides
        like data that would otherwise be inherited from the common player. This
        situation is different for fields that contain arrays. When the data
        type of the field is an array, you can choose the inheritance behavior
        to be overwrite, prepend or append. The fields whose data type is an
        array, and for which you can control inheritance behavior are: scripts,
        stylesheets, plugins, sources. You can add special field names to the
        configuration object to control array inheritance, and change the
        default behavior of embeds overriding common player data. If a array
        field in an embed's configuration has a child item called array_prepend
        or array_append the data will be correspondingly prepended or appended
        to the common player's data for the like field. ee the Array fields
        section of the Embeds Guide for a complete discussion.
      summary: Create an embed
      operationId: CreateEmbed
      security:
        - BC_OAuth2:
          - video-cloud/player/all
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/players/{player_id}/embeds/{embed_id}':
    get:
      tags:
        - Player Embeds
      summary: Get a specific embed for a player.
      description: Get a specific embed (child player) for a player.
      operationId: GetSingleEmbeds
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Player Embeds
      description: Delete a particular embed (child player) for a player.
      summary: Delete an embed
      operationId: DeleteEmbed
      security:
        - BC_OAuth2:
          - video-cloud/player/all
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/players/{player_id}/embeds/{embed_id}/configuration/{branch}':
    get:
      tags:
        - Embed Configurations
      summary: Get player embed configuration
      description: >-
        Get the configuration for an embed. You must specify the branch, either
        `master` or `preview`.
      operationId: GetEmbedConfiguration
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/players/{player_id}/embeds/{embed_id}/configuration/':
    patch:
      tags:
        - Embed Configurations
      summary: Update embed configuration
      description: >-
        Update the configuration for an embed. Note that you will need to
        publish the altered embed for optimization and production use. You can
        also use a `PUT` HTTP method instead of the `PATCH` shown here. When
        using `PUT` it replaces all embed configuration information, so you must
        supply all embed configuration information when using `PUT`. In
        contrast, `PATCH` appends or modifies existing configuration
        information. Using `PUT` is such rare use case it is not detailed in
        this reference.
      operationId: UpdateEmbedConfiguration
      security:
        - BC_OAuth2:
          - video-cloud/player/all
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/:account_id/players/:player_id/embeds/:embedID/configuration/merged':
    get:
      tags:
        - Embed Configurations
      summary: Get Configuration Combinations
      description: |-
        Retrieve the configuration for a parent/child combination of master and preview branches. If you are using the second query parameter (and hence using the ampersand [&]), you MUST use quotes around the endpoint or the curl statement will fail at the ampersand. For example:

        `"https://players.api.brightcove.com/v1/accounts/$ACCOUNT_ID/players/$PLAYER_ID/embeds/$EMBED_ID/configuration/merged?playerBranch=preview&embedBranch=master"`.

        Using this endpoint provides a way to view what the resulting configuration would be when combining different combinations of parent and child (also called embed) versions of players. Using this endpoint does not change any configurations, it is only useful for seeing results of merging changes to configurations.
      operationId: GetConfigurationCombinations
      security:
        - BC_OAuth2:
          - video-cloud/player/read
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: |-
        Brightcove OAuth API. See the [support documentation](/oauth/index.html) or [Getting Access Tokens](/oauth/code-samples/oauth-api-sample-get-access-token.html) to learn more.

        For development, the Player Management API also supports the `Basic` authorization header in the form `Authorization: Basic {username:password}` - the username and password here are those used for Video Cloud. the whole `username:password` string must be Base64 encoded (CURL does this automatically; for other languages you must encode the string manually)
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/player/read: Read player data
            video-cloud/player/all: Read/write player data
